config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/developers', to: "developers#index"
  root 'developers#index'

  namespace 'api' do
    namespace 'v1' do
      get '/developers', to: 'developers#index'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :developer_languages
  has_many :languages, through: :developer_languages
  has_many :developer_programming_languages
  has_many :programming_languages, through: :developer_programming_languages

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def programming_languages_list
    programming_languages.pluck(:name).join(", ")
  end

  def languages_list
    languages.pluck(:code).join(", ")
  end
end

app/models/developer_language.rb
class DeveloperLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :language
end

app/models/developer_programming_language.rb
class DeveloperProgrammingLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :developer_languages
  has_many :developers, through: :developer_languages

  validates :code, presence: true
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :developer_programming_languages
  has_many :developers, through: :developer_programming_languages

  validates :name, presence: true
end

app/controllers/api/v1/developers_controller.rb
class Api::V1::DevelopersController < ActionController::API 
  def index
    @developers = Developer.includes(:programming_languages, :languages)
    render json: DeveloperSerializer.new(@developers).serializable_hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @programming_language = params[:programming_language]
    @language = params[:language]
    @developers = SearchDeveloperService.new(params).call
    @count = @developers.present? ? @developers.count : 0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/index.slim
h1 Search Developers

= form_tag(developers_path, method: :get, enforce_utf8: false) do
  = label_tag "Programming Language"
  br
  = text_field_tag 'programming_language', @programming_language
  br
  = label_tag "Language"
  br
  = text_field_tag 'language', @language
  br
  = submit_tag 'Search', name: nil

- if @programming_language.present? || @language.present?
  - if @count < 2
    p= "Find #{@count} result with these keywords \"#{@programming_language + " " + @language}.strip\"" 
  - else
    p= "Find #{@count} results with these keywords \"#{@programming_language + " " + @language}\"" 
- if @developers.present?
  h2 Developer List
  table.developers-table
    thead
      tr
        th ID 
        th Email
        th Programming Languages
        th Languages
    tbody
      - @developers.each do |dev|
        tr
          td= dev.id
          td= dev.email
          td= dev.programming_languages_list
          td= dev.languages_list

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorExApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>